### ISSUE TITLE
Special keys not working

### ISSUE THREAD

**Issue by Taran98** [Steppschuh/RemoteControlServer#101]
Although the overall app works great but while using keyboard some keys like fullstop, comma, @ , # , &, / , * , + , " , : , etc don't work in bothe the cases of live transfer and non-live transfer. I have even tried reinstalling both the app and the server but still facing the same problem.

**Comment by Steppschuh** [comment]
Please let me know which exact server and app version you are using. The latest version of the server is able to process all UTF-8 characters and the latest app version is sending them without issues.

**Comment by Taran98** [comment]
i m using the latest version bro. My server version is- 3.1.1.12  and my
app version is 1.6.0.1

On Sun, Apr 12, 2015 at 4:47 PM, Stephan Schultz <notifications@github.com>
wrote:

> Please let me know which exact server and app version you are using. The
> latest version of the server is able to process all UTF-8 characters and
> the latest app version is sending them without issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Steppschuh/RemoteControlServer/issues/101#issuecomment-92035060>
> .
>



-- 

*From Taran*

**Comment by Steppschuh** [comment]
Just to let you know, 1.6 is over two years old.

  			 <http://steppschuh.net/> 			 	
Stephan Schultz <applewebdata://36184059-9F20-47EA-BE74-14DE7F8D8F2C/%E2%80%9Chttp://steppschuh.net%22>, Student
Hasso Plattner Institute <http://hpi.de/>
Facebook <https://www.facebook.com/Steppschuh> • Google+ <https://plus.google.com/+StephanSchultz> • LinkedIn <https://www.linkedin.com/in/Steppschuh>

**Comment by Taran98** [comment]
but on my play store it is the latest version showing.


On Sun, Apr 12, 2015 at 10:24 PM, Stephan Schultz <notifications@github.com>
wrote:

> Just to let you know, 1.6 is over two years old.
>
> <http://steppschuh.net/>
> Stephan Schultz
> <applewebdata://36184059-9F20-47EA-BE74-14DE7F8D8F2C/%E2%80%9Chttp://
> steppschuh.net%22>, Student
> Hasso Plattner Institute <http://hpi.de/>
> Facebook <https://www.facebook.com/Steppschuh> • Google+ <
> https://plus.google.com/+StephanSchultz> • LinkedIn <
> https://www.linkedin.com/in/Steppschuh>
>
>
>
>
> > On 12 Apr 2015, at 18:41, Taran98 <notifications@github.com> wrote:
> >
> > i m using the latest version bro. My server version is- 3.1.1.12 and my
> > app version is 1.6.0.1
> >
> > On Sun, Apr 12, 2015 at 4:47 PM, Stephan Schultz <
> notifications@github.com>
> > wrote:
> >
> > > Please let me know which exact server and app version you are using.
> The
> > > latest version of the server is able to process all UTF-8 characters
> and
> > > the latest app version is sending them without issues.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/Steppschuh/RemoteControlServer/issues/101#issuecomment-92035060
> >
> > > .
> > >
> >
> >
> >
> > --
> >
> > *From Taran*
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/Steppschuh/RemoteControlServer/issues/101#issuecomment-92086051
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Steppschuh/RemoteControlServer/issues/101#issuecomment-92087347>
> .
>



-- 

*From Taran*

**Comment by Steppschuh** [comment]
You might need to upgrade your device. You are currently using Android Gingerbread, which has been released 5 years ago and doesn't support up to date apps anymore.

**Comment by Taran98** [comment]
Okey i will root my phone.
