### ISSUE TITLE
scroll wheel on my mouse no longer scrolls, instead it controls the zoom percent.

### ISSUE THREAD

**Issue by tcarrw** [Steppschuh/RemoteControlServer#103]
My computer mouse no loners scrolls with the scroll wheel. Now when I try to scroll it changes the page zoom level. How do I revert this change?

**Comment by tcarrw** [comment]
Somehow the Ctrl key was stickied down and was causing this issue. It would be nice to know if a key is stickied down and affecting everything.

**Comment by Steppschuh** [comment]
The keyboard remote sends a key down event when you touch a key, and a key up event if you release it. Seems like your router dropped the data package, resulting not lifting the key up.
