### ISSUE TITLE
Do you have to purchase the Pro version for each device type i.e. android, apple you want to use?

### ISSUE THREAD

**Issue by ioosechange** [Steppschuh/RemoteControlServer#110]
I purchased the Pro version while using my Android device with the intention to also use the app on on my ipad but I can't seem to figure out how to activate Pro functionality on my iPad as well. Do I have to purchase another Pro license for each device type I want to use to manage my laptop with?

**Comment by Steppschuh** [comment]
If you have purchased the pro version on your Android device, it will be available on all your Android devices. Same thing with iOS and BlackBerry. You can't mix between these ecosystems, though.
