### ISSUE TITLE
Errors when start server in w7

### ISSUE THREAD

**Issue by AlvaroRomero** [Steppschuh/RemoteControlServer#113]
Details errors showed when start server in windows 7:

Firma con problemas:
  Nombre del evento de problema:	CLR20r3
  Firma del problema 01:	remote control server.exe
  Firma del problema 02:	3.0.2.13
  Firma del problema 03:	54bd43dc
  Firma del problema 04:	Remote Control Server
  Firma del problema 05:	3.0.2.13
  Firma del problema 06:	54bd43dc
  Firma del problema 07:	1e3
  Firma del problema 08:	6f
  Firma del problema 09:	System.NullReferenceException
  Versión del sistema operativo:	6.1.7601.2.1.0.768.2
  Id. de configuración regional:	11274
  Información adicional 1:	46e4
  Información adicional 2:	46e48e8803f91cd8aca67e97005f2e98
  Información adicional 3:	4ae4
  Información adicional 4:	4ae489e6e3deac2d00560cf8ad5b3925

  
  ---------------------------------------------------------
  
  Firma con problemas:
  Nombre del evento de problema:	APPCRASH
  Nombre de la aplicación:	Remote Control Server.exe
  Versión de la aplicación:	3.0.2.13
  Marca de tiempo de la aplicación:	54bd43dc
  Nombre del módulo con errores:	KERNELBASE.dll
  Versión del módulo con errores:	6.1.7601.18015
  Marca de tiempo del módulo con errores:	50b8479b
  Código de excepción:	c000041d
  Desplazamiento de excepción:	0000000000009e5d
  Versión del sistema operativo:	6.1.7601.2.1.0.768.2
  Id. de configuración regional:	11274
  Información adicional 1:	bcdf
  Información adicional 2:	bcdfce8a734ce0fa3d8d978ed8ba1cae
  Información adicional 3:	32d0
  Información adicional 4:	32d0a3573d31dc26ac47d409a85a67d3

**Comment by Steppschuh** [comment]
https://github.com/Steppschuh/RemoteControlServer/issues/52
