### ISSUE TITLE
Can't click

### ISSUE THREAD

**Issue by sirmars** [Steppschuh/RemoteControlServer#114]
Hi, I can't click via the remote mouse. The cursor moves just fine but I can't get it to click. I'm tapping the icons for the clicking but nothing is happening. In the beginning when I installed it there was a huuuuge delay in the clicking and then  it completely stopped working. Please help as soon as possible. Thank you!

**Comment by Steppschuh** [comment]
While moving the cursor are UDP commands, clicking and other remotes are TCP commands. I guess your Firewall is blocking the TCP data packages, please follow the instructions shown here:
http://remote-control-collection.com/help/troubleshooting/
