### ISSUE TITLE
Keyboard mode crashes app

### ISSUE THREAD

**Issue by BGMcoder** [Steppschuh/RemoteControlServer#124]
Android 4.0.3 on an Acer Iconia Tablet A100; Windows 7 Pro x64.
Remote Input app 1.7.2.31
Remote Control Server 3.1.1.12

The mouse mode works just fine.  But if I switch to keyboard mode, the live transfer always crashes the app on the android.  The app reports "Unfortunately, Remote Input has stopped working".  It will send one character then "stop working".

**Comment by Steppschuh** [comment]
Hey,
please not that you are not using an up to date app version. Please update to version 3.4.3.7 and let me know if you are still having issues.

**Comment by BGMcoder** [comment]
I just installed the app two days ago.  I'll check again for updates.

**Comment by Steppschuh** [comment]
Keep in mind that your device may not support newer versions because you are using an old Android version.

**Comment by BGMcoder** [comment]
Ah; so what do I do?  I just got it from google play.

**Comment by Steppschuh** [comment]
Upgrade your device. You might have luck and can use a more up to date version of the Remote Control Collection: https://play.google.com/store/apps/details?id=com.steppschuh.remotecontrolcollection

**Comment by BGMcoder** [comment]
Okay, I suppose there's nothing to be done.  I cannot upgrade Android on the tablet past 4.0.3, and when I install the app on the device it still shows version 1.7.2.31.  Will my Android version support a higher version of Remote Input, and can I download a newer version directly somewhere?

**Comment by BGMcoder** [comment]
I think that *other than you providing me with a link to a different apk that you think would work for me*, that the only way to get a different version of your remote control app is to figure out how to spoof my android's device id so that google play thinks it is a different android version.

**Comment by BGMcoder** [comment]
Okay, I spoofed my device and installed a package meant for a Nexus 7: 
https://addons.mozilla.org/en-US/firefox/addon/apk-downloader/?src=search
https://play.google.com/store/apps/details?id=com.redphx.deviceid&hl=en
http://codekiem.com/2013/02/13/market-helper/
Now I have version 2.2.1.91 and the keyboard remote does not crash.
