### ISSUE TITLE
Unable to connect, device unavailable

### ISSUE THREAD

**Issue by verotoledo** [Steppschuh/RemoteControlServer#127]
I cant connect to my pc. I have tried everything on the troubleshoting page and nothing works. My pc isn't blocking the app, they are both connected to the same wifi, the withelist is not enabled I also tried the ping and it came out normal. The app keeps saying that my laptop is unavailable. I don't know what else to do. Please help

**Comment by Steppschuh** [comment]
Hey,
if the ping works that's a good sign. Please make sure that you disabled all firewalls and AntiVir tools while troubleshooting. Also try starting the server with administrator rights.

if you're still having issues, please let me know:
- Which app version you are using
- Which server version you are using
- Server log output after you tried to connect

**Comment by verotoledo** [comment]
Hey I found out that my Anti virus was blocking the app. Thanks

**Comment by samkitsheth** [comment]
I am also facing the same problem. I disabled the firewall from my antivirus but stil the same problem is persisting. Kindly help.

Thanks
