### ISSUE TITLE
Connect devices in different networks

### ISSUE THREAD

**Issue by FriendlyOscar** [Steppschuh/RemoteControlServer#128]
My network cannot let my phone and PC in the same network, so can I?

**Comment by Steppschuh** [comment]
Hey,
you can only connect devices in different networks if you use [VPN](https://en.wikipedia.org/wiki/Virtual_private_network) to tunnel all requests from your phone to your PCs network. I personally wouldn't do that, it's easier to set up a new network and connect both devices to it. You could use tools like [Connectify](http://www.connectify.me/) for that.
