### ISSUE TITLE
No se me conecta 

### ISSUE THREAD

**Issue by cawaquiroz** [Steppschuh/RemoteControlServer#131]
hola, inicio la app y el servidor de la pc, como siempre lo hago, pero ahora no se me conecta,ya probre desactivando el antivirus. cuando trato de conectarlo desde el celular, me dice "unavailable". ya controle la IP y esta perfecta

**Comment by cawaquiroz** [comment]
por lo que pude notar la IP del servidor es distinta a la de mi red,como se cambia?

**Comment by Steppschuh** [comment]
Yes, the IP address is local only and depends on your network. It's supposed to be different that you mobile device IP. Please refer to the help and troubleshooting section to learn more:
remote-control-collection.com/help/troubleshooting/
