### ISSUE TITLE
windows viewer?

### ISSUE THREAD

**Issue by drogit** [Steppschuh/RemoteControlServer#139]
am i missing something?  does it handle windows to windows via internet?  i mean the remote is windows (whatever version) and be controlled by windows desktop? or is just via mobile device?

**Comment by Steppschuh** [comment]
As every description states, the Remote Control Server handles commands from the [Remote Control Collection](http://remote-control-collection.com/) apps. They can be used to control your PC or Mac from an Android or iOS device.

**Comment by drogit** [comment]
i am sorry buddy - i not so bright but i assume that your answer means no, it does not.  you cannot control a windows pc screen from a windows desktop app, just blackberry, android and ios right?

**Comment by Steppschuh** [comment]
Exactly. There's no Remote Control Collection app available for Windows.
