### ISSUE TITLE
Remote collection pro was paid, and looks like free version.

### ISSUE THREAD

**Issue by matheusaz** [Steppschuh/RemoteControlServer#141]
Well, I paid for the pro version, which is around 10 brazilian reais (around 2,5 dollars) and when I used it, it was no different from the free version. My desktop use, the slides mode and midia are all blocked. And the ad's are all here too :/ just need to know if i have to use some code or anything. The only possibility that i found, was to pay for which one and its even more expensive and it was like I paid 2,5 dollars for nothing. 

plz help :p

**Comment by Steppschuh** [comment]
Hey,
have you paid for an in-app upgrade or have you purchased the stand-alone pro version (red icon)?
Either way, please make sure that open the app with a working internet connection and while signed in to Google Play with the same account that you used for purchasing.

**Comment by matheusaz** [comment]
Red icon on my android. internet is ok. 

well, maybe the google play thing. Lets try it out

**Comment by matheusaz** [comment]
well, i was logged at the google play, and logged now. How do I make the app to recognize it? 

other aplications are recognizing. 

There's a login place on app?

**Comment by matheusaz** [comment]
i'm still with the problem. Help!!! :p

**Comment by Steppschuh** [comment]
The app with the red icon does not have any blocked remotes or ads at all. This would only be the case in the free app (blue icon). I assume that you are using the wrong app.

Anyway, please let me know your order ID (you received it right after your purchase via mail from Google). I'll look into it and send you a refund. You can then get whatever version you want.

**Comment by matheusaz** [comment]
Número do pedido: GPA.1312-6741-1604-94781
Data do pedido: 28/07/2016 1h15min45s BRT

**Comment by matheusaz** [comment]
i think, something went wrong at the installation, and I had installed the blue one. now, i have installed the right one! thank you!!
