### ISSUE TITLE
Remote Control Server has stopped working [unsolved]

### ISSUE THREAD

**Issue by chlora** [Steppschuh/RemoteControlServer#149]
Hi Steppshuh, 

Remote Control Server has not been able to run on my Windows PC, I've been encountering this issue since 2015, thinking a patch or new version would solve this. After installing the server and running it (with or without admin privileges), I get a prompt saying "Remote Control Server has stopped working", Windows doesn't provide the details. The white box in the image is the application failing to display.

![stopped_working](https://cloud.githubusercontent.com/assets/25203556/22070399/d9663740-dd69-11e6-95a7-a6d56f842bd4.PNG)

I'm running Windows 10 Pro x64 and believe I have followed ALL your suggestions in similar posts with no luck at all:
https://github.com/Steppschuh/RemoteControlServer/issues/68
https://github.com/Steppschuh/RemoteControlServer/issues/65

I have attempted reinstalling several times, deleting the config, trying to install the latest .NET framework (I already have the latest version), tried changing the installation directory, tried admin privileges, tried deleting the folder from AppData, but the application just doesn't run.

Other users in similar posts were able to work around this message as their application still ran even though they were prompted with a similar message. My application doesn't run at all so I can't connect to my server. Please assist me with a working fix or suggestions.

**Comment by Steppschuh** [comment]
Hey,
sorry to hear that. Unfortunately there's not much I can do, as there's no error log. I also use the server on a Win 10 Pro x64 with the latest .NET framework, but I'm unable to reproduce the crash.

If you're sure that you already did a clean uninstall and that there are no more old config files around, I can't think of any more troubleshooting tips.

**Comment by chlora** [comment]
If it's any help, I tried choosing debug and chose Microsoft Visual Studio 2015 as my debugger. I don't have a license for Visual Studio 2015, but here is the message that was displayed. 

![visual studio debug](https://cloud.githubusercontent.com/assets/25203556/22075572/8159cf4c-dd7a-11e6-9e26-563edde1a6a8.PNG)

"Socket exception unhandled"

**Comment by Steppschuh** [comment]
Thanks for investigating further. Unfortunately this is still a very generic message. I'll see if I can somehow reproduce it.

**Comment by E-T-2017** [comment]
Hey @chlora 

I experienced the same problem and I found a fix. Apparently, it's a common bug.
Here's the thread where I found the fix:

https://github.com/Steppschuh/RemoteControlServer/issues/52

Hope that helps. Helped with me though.

Cheers!
