### ISSUE TITLE
App doesn't detect server anymore

### ISSUE THREAD

**Issue by PyroZorion** [Steppschuh/RemoteControlServer#163]
It has stopped working suddenly. From one day to the next, the android app does not detect the server even if it is operative.

**Comment by Steppschuh** [comment]
Hey,
as the server and app haven't changed a thing, it's probably your network setup or devices that changed. Please follow the [troubleshooting guide](http://remote-control-collection.com/help/troubleshooting/) to check what is causing the issue.
