### ISSUE TITLE
No control when opening Admin dialogs

### ISSUE THREAD

**Issue by skullster704** [Steppschuh/RemoteControlServer#48]
The server appears to stop responding on appearance of a User Account Control dialogue in Windows 7 Home Premium.

The server responds correctly prior to the dialogue appearing, then stops responding to tablet input (mouse or keyboard), and does not begin responding again until the server is restarted.

This occurred on an Adobe update, and when clearing restoring Chrome to default settings.

**Comment by zachsaw** [comment]
This is not dissimilar to how VNC get around the UAC dialogue and elevated processes. It is definitely doable and had nothing to do with .Net framework.

**Comment by Steppschuh** [comment]
VNC is a very different approach and although it offers similar features it works in a completely different way than the Remote Control Server. You can read more about that topic here: https://en.wikipedia.org/wiki/Virtual_Network_Computing

**Comment by zachsaw** [comment]
It is certainly doable via .NET framework using the same techniques shown in VNC. Whether you're interested or not (obvious you're not) is another matter.

**Comment by Steppschuh** [comment]
No doubt in that, but it's not possible using the approach that the Remote Control Server is using. It has ups and downs, one of the downs being the lack UAC access. Please don't think I wouldn't be interested in the project that I grew up from scratch in my limited spare time 3 years ago. Decisions were made, and  they were made for a reason.
