### ISSUE TITLE
Server always starts settings window, not minimised

### ISSUE THREAD

**Issue by BevanFindlay** [Steppschuh/RemoteControlServer#56]
I have installed the server, enabled the options "Start server when Windows starts" and "Start server minimised", however whenever the computer starts up, the settings window appears (not minimised).  I cannot see how to stop it doing this.

**Comment by GrijzeGeest** [comment]
Same problem here: version 2.2.3.24

Uninstalled, deleted all remaining files, reinstalled: same problem

Always starts as shown in the picture
![remote](https://cloud.githubusercontent.com/assets/10475620/5691571/1622a8c2-98ce-11e4-8bb8-139edc81eab0.PNG)

Also both startup options are unchecked when it restarts even though it does start at startup (Start server when windows starts & start server minimized)

**Comment by TomBeckett** [comment]
This occurs because the setting **showGuide** is enabled within the GUI initialize Sub. 

Currently I am unable to make a PR to fix.

**Comment by Steppschuh** [comment]
The server will always show this window, if it thinks that you never connected to it before. If you connect your device once, it won't show up again.

However, if you don't close the server and let Windows kill it (for whatever reason), the server can't save its settings and will forget that you established a connection before.

**Comment by Steppschuh** [comment]
To manually set the option, you can close the server and directly edit the config file located at:

`C:\Users\<Your user name>\AppData\Roaming\Remote Control Server\`

Add or update the property `showGuide` with a value of `0`.

Save the config, restart the server and the guide should not appear again.
