### ISSUE TITLE
Server crash - Problem Event Name CLR20r3

### ISSUE THREAD

**Issue by DeckStarg** [Steppschuh/RemoteControlServer#68]
Everytime I start up the server file, I get the above mentioned error, and attachements below.  The app continues to work if I leave the server interface (phone) on the screen but as soon as I minimise it then the app crashes. I then move my mouse over the small icon on the taskbar and the icon disappears.  
I have searched the net for fixes and tried them all, from verifying the integrity of .Net Framework 4.0 as well as using the CMD fix but still no luck. I have also tried fixing the registry with a scan but also no luck. Please can you assist?
![remot control server error1](https://cloud.githubusercontent.com/assets/9691521/5006817/102f4958-6a51-11e4-9077-37bd7bb77639.JPG)
![remot control server error2](https://cloud.githubusercontent.com/assets/9691521/5006819/15ead1e6-6a51-11e4-9f31-77d50b3e1369.JPG)

**Comment by marvx6** [comment]
this doesn't work for me.
Is there another workaround? It's very annoying to hit two times "close the program" after booting up.

BRr,
Marvin

**Comment by DeckStarg** [comment]
Hi Stephan

This fix isn't working anymore.  Any other suggestions please?

Running Windows 7 Ultimate x64

**Comment by Steppschuh** [comment]
What exactly are the crash reports you are seeing? They might are caused by something different than an outdated config file.

**Comment by DeckStarg** [comment]
Well, I submitted a ticket via GitHub a while ago, while I was running
Windows 7.  This problem never got solved.  The latest version of your app
seems to work well with Windows 10 but I have had endless issues with the
app on Windows 7.  I recently downgraded back to Windows 7, as I hated
Windows 10.

I have attached screenshots of the exact error codes.  These errors come up
ever single time I launch the application on the PC and it comes up twice.
After I click on CLOSE THE PROGRAM after the first error message, I get
another error message straight afterwards and I click CLOSE THE PROGRAM
again.  After the second time, the app continues to run.

Please come up with a solution.

Thanks

**Comment by Steppschuh** [comment]
I'd suggest uninstalling the server from your PC, deleting the appdata folder at `C:\Users\<Your user name>\AppData\Roaming\Remote Control Server\` and installing the latest [.NET framework](http://www.microsoft.com/net).

After that reinstall the latest server version and start it with administrator rights.

**Comment by DeckStarg** [comment]
Hi Stephan

I have the latest version of Net Framework already, 4.5. I'll try uninstall
in the app and reinstalling. I'm just scared that some of the apps files
will remain in the registry. Don't you have some removal app that I can
make sure there are no traces left behind after the uninstall?

**Comment by Steppschuh** [comment]
The server doesn't store any registry entries, except if you enabled the server to load when Windows starts. The 'removal app' will be invoked when you uninstall the server like [this](http://windows.microsoft.com/en-us/windows/uninstall-change-program#uninstall-change-program=windows-7)
