### ISSUE TITLE
Remote Control Server network initialization failed

### ISSUE THREAD

**Issue by ircle** [Steppschuh/RemoteControlServer#69]
whenever i run the server on my pc it comes up with," Network initialization failed, not all listeners could be started." and on my phone it says,"error: the server is unreachable." I've tried everything i can to get this to work and i cant do it. I'm about to just give up and uninstall. please help

**Comment by Killinglizards** [comment]
Hi,
Same problem here.
When i try to connect to the remote collection server with my phone, it says "not available" on the app on my phone, even with the correct address setle up within the server, and the, when i try to close the server (program) on pc give me this error:

Microsoft .NET Framework

Eccezione non gestita in un componente dell'applicazione. Fare cli su Continua per ignorare e tentare di proseguire.

Impossibile impostare visibility o chiamare show, ShowDialog o WindowsinteropHelper.EnsureHandle dopo la chiusura dell'oggetto window.

Dettagli:
Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.InvalidOperationException: Impossibile impostare Visibility o chiamare Show, ShowDialog o WindowInteropHelper.EnsureHandle dopo la chiusura dell'oggetto Window.
   in System.Windows.Window.VerifyCanShow()
   in System.Windows.Window.CoerceVisibility(DependencyObject d, Object value)
   in System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   in System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   in RemoteControlServer.MainWindow.showUI()
   in RemoteControlServer.MainWindow.NotifyIcon_Click(Object sender, EventArgs e)
   in System.Windows.Forms.NotifyIcon.OnClick(EventArgs e)
   in System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
   in System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4420.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Remote Control Server
    Versione assembly: 3.1.1.12
    Versione Win32: 3.1.1.12
    Base di codice: file:///C:/Program%20Files%20(x86)/Remote%20Control%20Server/Remote%20Control%20Server.exe
----------------------------------------
PresentationFramework
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4455.0
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4455.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4455.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4360.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4455.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4455.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.VisualBasic
    Versione assembly: 10.0.0.0
    Versione Win32: 14.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
PresentationFramework.Aero2
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
PresentationFramework-SystemXml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationCore.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationCore.resources/v4.0_4.0.0.0_it_31bf3856ad364e35/PresentationCore.resources.dll
----------------------------------------
UIAutomationTypes
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4455.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4455.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4400.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.xml.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Xml.resources.dll
----------------------------------------
PresentationFramework.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.resources/v4.0_4.0.0.0_it_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.





Someone can suggest?
Sincerely
