### ISSUE TITLE
Problems with smartphone IP

### ISSUE THREAD

**Issue by douggienator** [Steppschuh/RemoteControlServer#83]
My smartphone tries to connect with two different IP adresses alternately, which makes my server to demand for PIN code everytime my smartphone decides to change IP (every three seconds). Is there a way to add the devicce to a whitelist, or something?

**Comment by Steppschuh** [comment]
I highly doubt that your smartphones IP address changes. If it does, something is wrong with your device or network. You smartphone can only get a new IP if it reconnects to your router - and it obviously shouldn't drop the connection every 3 seconds.

You could try to assign a static IP address for your smartphone in your network settings. Nothing that the server could fix, unfortunately.
