### ISSUE TITLE
Speech recognition

### ISSUE THREAD

**Issue by alan1969** [Steppschuh/RemoteControlServer#88]
Hi Stephan, have you dropped the speech recognition function? My dyslexic friend uses the full version for voice typing on her computer. Oddly the microphone does' t appear on the android keyboard. I had a .apk from an old version that I side loaded on so she's back to sending emails. Thanks.

**Comment by Steppschuh** [comment]
There will be an improved version of the speech recognition in the new app, but it wasn't ready for the latest update yet. Keep an eye open for upcoming versions.
