### ISSUE TITLE
Using a signal extender

### ISSUE THREAD

**Issue by diaslunatic** [Steppschuh/RemoteControlServer#89]
I use a signal extender, my PC is connected to the Signal Extender, and my Cellphone is connected to the Main Router. My PC has one IP, and my Cellphone another, am I still able to use it? It's failing to connect.

**Comment by Steppschuh** [comment]
You should check if you can ping your cellphone IP from your PC. If it is reachable, the connection should work. If not, you may need to check your routers admin panel. There could be an option active that blocks communication between connected network devices - make sure that this is disabled.
