### ISSUE TITLE
Where is the standby button now ?

### ISSUE THREAD

**Issue by LaurentBarbareau** [Steppschuh/RemoteControlServer#92]
Hi,
I've update my Android app to version 3.2.2.3 and then now, I don't have the standby button anymore ?
I just can shutdown my PC but this is absolutely not the same thing...
Is it a bug or you've really removed that functionality ? 

It is the most important command for me, I use it everyday ! Please put it back.

Moreover, as enhancements, maybe you could let users add some favorite shortcuts somewhere, always very fast and easy to access. Wouldn't it be nice ?

Thx

**Comment by Steppschuh** [comment]
You can use the custom keys for that now. Simply create a batch file for that, see:
http://superuser.com/questions/145400/sleeping-a-computer-via-batch-file-in-windows-7
