### ISSUE TITLE
Keyboard haptic feedback, and dark theme for new UI

### ISSUE THREAD

**Issue by iceeyhot** [Steppschuh/RemoteControlServer#93]
Is there a way to disable haptic feedback when using the keyboard remote?  If not could an option be put into the next version?

Also, I love the new UI, but could you bring back the old dark theme option from previous versions?

**Comment by Steppschuh** [comment]
There will be an option in the settings to disable haptic feedback in the upcoming version.

The UI won't change, the app will keep following Googles design guidelines.
