### ISSUE TITLE
Can`t connect due to dual WiFi technology

### ISSUE THREAD

**Issue by grigorexxl** [Steppschuh/RemoteControlServer#95]
Hi, i have this strange problem wherre i can`t conect trough my new modem/router that was given to me by my ISP witch had changed their technology recently by passing to what is called "fiber" internet here in Italy. It seems like, for what i`ve discovered, the modem has both 2,4ghz as 5ghz WiFi technology built in and thats probably the issue herre (allready tried to function only on 2.4ghz or the 5ghz by shuting down one of them), because i allready used the software on other modem/routers, so no need for firewall tweeks nor port openings. I would very much be pleased if you can come whit a solution for this problem. Thx, and you are doing a great job.
P.S: the ISP is "TELECOM" and hardware is made by "Technicolor" Italy and bears the name "TELECOM" on it, and it`s made in Vietnam

**Comment by Steppschuh** [comment]
The 2.4 and 5.0 GHz are not a problem. I use the app in a network powered by both frequencies simultaneously. I guess your new router simply has options active that block the communication between network devices, please doublecheck that.

Use the ping command to check if your setup is alright, as described in the troubleshooting guide:
http://remote-control-collection.com/help/troubleshooting/
