### ISSUE TITLE
Command-line options?

### ISSUE THREAD

**Issue by shawnkhall** [Steppschuh/RemoteControlServer#97]
Are there any command line options or other way to automate the process of closing and reopening RemoteControlServer and making configuration changes?

**Comment by Steppschuh** [comment]
There are none, but may I ask why you want

**Comment by Steppschuh** [comment]
There are none, but may I ask what exactly you want to do? You can manually edit the config file,
it's located at:
C:\Users\<Your user name>\AppData\Roaming\Remote Control Server\

**Comment by shawnkhall** [comment]
I have several devices I pop between and with the sticky mouse problem that the server exposes I can't leave it open unless I'm using it, but I won't always know I want it open when I need it, nor that I'm done with it when I'm done. 

I'd like to be able to easily turn it on and off via the command line. I already use other tools to access my devices to operate a shell on them now. 

Ideally, it would be something as easy as "net start rccs" or "net stop rccs", but should be at least scriptable so that I can queue a quit with something like ["C:\Program Files (x86)\Remote Control Server\Remote Control Server.exe" /quit] to close it. 

Otherwise I'll have to kill it which might result in a memory leak or other problems.
